/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.educativaproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author adrie
 */
public class LoginFrame extends javax.swing.JFrame {
    int tentativas = 3;
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setExtendedState(500);
    }
    
    public String qtdTentativas(){
        tentativas--;
        return "Senha incorreta! Tentativas restantes: " + tentativas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 800, 800));
        setSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Senha");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        btnLogin.setBackground(new java.awt.Color(47, 72, 88));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setBorder(null);
        btnLogin.setBorderPainted(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 340, 40));

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Cadastrar");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, -1, -1));

        jLabel3.setText("Esqueci minha senha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 340, 40));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 340, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoEducativa.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        PerfilFrame perfil = new PerfilFrame();
        //cria objeto da classe conexão
        ConnectionFactory connection = new ConnectionFactory();
        //variavel da classe preparedStatement que carrega o script 
        PreparedStatement pstmt = null;
        PreparedStatement pstmtProf = null;
        //cria variavel que carrega os valores da caixa de texto
        String emailTest = txtEmail.getText(); 
        //cria variavel que carrega os valores da caixa de texto
        String senhaTest = new String(txtPassword.getPassword());
        boolean usuarioEncontrado = false;
        
        if(!emailTest.isEmpty() && !senhaTest.isEmpty()){
            
            if(tentativas > 0){
                try(Connection c = connection.conexao()){
           
                pstmt = c.prepareStatement("SELECT * FROM tb_aluno");
                ResultSet result = pstmt.executeQuery();
                pstmtProf = c.prepareStatement("SELECT * FROM tb_professor");
                ResultSet result2 = pstmtProf.executeQuery();
                



                while(result.next()){
                    String email = result.getString("emailAluno");
                    String senha = result.getString("senhaAluno");
                    if(email.equals(txtEmail.getText()) && senha.equals(new String(txtPassword.getPassword()))){ 
                        this.dispose();
                        perfil.moveParam(result.getString("nomeAluno"), result.getString("emailAluno"), result.getString("cpfAluno"), result.getString("senhaAluno"), result.getInt("idAluno"));
                        perfil.setVisible(true);
                        usuarioEncontrado = true;
                    }

                }

                if(result2.next()){
                    String email2 = result2.getString("emailProfessor");
                    String senha2 = result2.getString("senhaProfessor");
                    if(email2.equals(txtEmail.getText()) && senha2.equals(new String(txtPassword.getPassword()))){
                        this.dispose();
                        perfil.moveParam(result2.getString("nomeProfessor"), result2.getString("emailProfessor"), result2.getString("cpfProfessor"), result2.getString("senhaProfessor"), result2.getInt("idProfessor"));
                        perfil.setVisible(true);
                        usuarioEncontrado = true;
                    }
                }

                //JOptionPane.showMessageDialog(null, "Campo email ou senha inválidos");

                }catch (Exception e){
                    e.printStackTrace();
                }
                
                if(usuarioEncontrado == false){
                    JOptionPane.showMessageDialog(null, this.qtdTentativas());
                }
                
                
                
            }else{
                JOptionPane.showMessageDialog(null, "Tente novamente mais tarde");
            }

            
            
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Campo email ou senha não preenchido");
        }
        

        

        
        
        
        
        
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        CadAlunoFrame frameAluno = new CadAlunoFrame();
        frameAluno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
